[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# StockApp

## Frontend

### StockTrader

#### As a stock trader, I want to manage my stock ticker symbols\. \(Must\)
> fillColor=`#FF5600`


##### As a stock trader, I want to view my stock ticker price history\. \(Must\)
> fillColor=`#FF5600`


##### As a stock trader, I want to group my stock ticker symbols\. \(Could\)

#### Get recommendations on popular stocks to follow

#### Portfolios for Retirement and Investment Accounts

#### As a stock trader, I want to buy and sell stocks\. \(Wont\)

#### As a stock trader, I want 2 factor authentication to login\. \(Should\)

#### As a stock trader, I want to recover a lost password\. \(Should\)

### Admin

#### As a site admin, I want to manage stock traders\. \(Should\)

#### As a site admin, I want to manage stock exchanges\. \(Should\)

### Visitor

#### Stock related news

#### View a stock's company information and SEC Filings

#### View stock performance charts \(1\)

#### As a visitor, I want to create a stock trader account\. \(Should\)

#### As a site user, I want to report a problem\. \(Could\)

## Backend

### Admin

#### As an admin, I want to manage stock traders\. \(Must\)
> fillColor=`#FF5600`


##### As an admin, I want to view stock trader usage reports \(Should\)

#### As an admin, I want to manage stock tickers\. \(Must\)
> fillColor=`#FF5600`


##### As an admin, I want to manage stock ticker price history\. \(Should\)

#### As an admin, I want to manage stock price API sources \(Must\)
> fillColor=`#FF5600`


#### As an admin, I want to manage stock exchanges \(Should\)

### Cron

#### As a cron / automation user, I want to batch update stock ticker price history\. \(Must\)
> fillColor=`#FF5600`


#### As a cron / automation user, I want to notify stock brokers of price updates\. \(Should\)

### Supervisor

#### As a supervisor, I want to manage admin accounts \(Must\)
> fillColor=`#FF5600`


### User

#### As a backend user, I want 2 factor authentication to log in\. \(Should\)

## Sean/Michael \(day\)
> leftSide=`true`


### Stock Info

## De'Saan/Tanner \(evening\)
> leftSide=`true`


### User Management

## Les/Juan \(evenings\)
> leftSide=`true`


### Batch Processing
